### ISSUE TITLE
GDPR Statement

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/BlueCross#112]
Hey @kellygrellier, 
Do you have the GDPR statement? 
Jen

**Comment by kellygrellier** [comment]
Hi @Jen-Harris 
We will need two statements:
1. 
We will be in touch within 2 days to arrange a time to come and see you and **'name of dog'**, when we will plan **'his'** rehoming journey and any further support you need - please tick if you are happy for us to contact you about finding **'name of dog'**  a new home by phone (tick box) and email (tick box) 
2.
Blue Cross would like to tell you about the great work we do for pets and the different ways in which you could support us, this may include fundraising activities, appeals and merchandise. 
Please tick below if you are happy for us to contact you by:
Mail	
Phone
Email
Text Message
You can unsubscribe or change your preferences at any time by contacting our Supporter Care team on 0300 790 9903 or emailing info@bluecross.org.uk
Blue Cross respects your privacy and will keep your information safe and secure and will only use them in accordance with our Privacy Policy. We will not sell, rent or share your personal data with other organisations for their marketing purposes. We may use your data for profiling purposes to make future communications more relevant to you. To see more about how we will use your information visit bluecross.org.uk/privacy

**Comment by kellygrellier** [comment]
Hi @Jen-Harris,
I hope you had a great weekend!
I realise this is very wordy, do you think this needs to be a page before thank-you so that it is clear that they need to opt in, in order for us to contact them about rehoming their pet?  Also It would be useful to take their physical address as part of this as well...is it too late to do that on the your details page?

Do you think the bit about saying goodbye to a much loved pet should then be on the thank-you page after a shorter we will be in touch with two days?  Something like:
We will look forward to speaking with you over the next couple of days about finding a great new home for 'name of dog'.
  
We know saying goodbye to, a much loved pet is hard, if you also need somebody to talk to about this, details of our confidential Pet Bereavement Support Service can be found here. 

What do you think?

**Comment by Jen-Harris** [comment]
Hi @kellygrellier,
It is quite wordy but I think users expect these kind of things now! It's probably best to keep it on the same page as the owner details rather than extending the flow further.

**Comment by kellygrellier** [comment]
Thanks @Jen-Harris,

I have opened a new issue to add a link to the Blue Cross Privacy & Cookie policy at the bottom of each page, this then covers us from a GDPR perspective.

Thanks very much, Kelly

**Comment by Jen-Harris** [comment]
@kellygrellier, is the first statement required for legal reasons? 
It may be easier to ask how they would prefer to be contacted as an option? for example: 
![image](https://user-images.githubusercontent.com/26116988/37036262-07021850-2147-11e8-91a1-bc15f8a1dabe.png)

**Comment by kellygrellier** [comment]
Hi @Jen-Harris,

No the first one isn't legal and I was thinking we could leave it to, 
"we will be in touch within 2 days to help you find a new home for 'name of dog'" 
Rather than giving them the choice as we would rather call them.

Our legal secretary said that as they have filled out the form then they are requesting our services so it is fine to not ask them to confirm.

Thanks and sorry for being confusing!

**Comment by Jen-Harris** [comment]
Ok great, so we can remove the question and just keep in the second GDPR statement. 

One other question is that we ask if they want to receive mail but we aren't taking their address. Is this something you would like included?

**Comment by kellygrellier** [comment]
Hi Jen,

Yes please if possible to get their address in their details that would be
perfect - sorry!  We will need to know where they live for the service too.

All the best, Kelly

**Comment by Jen-Harris** [comment]
Would a postcode be enough or would you require full address do you think?

**Comment by kellygrellier** [comment]
Perhaps just first line 7 postcode?

**Comment by kellygrellier** [comment]
Hi @Jen-Harris 
I think the first line of address & postcode would be good.

**Comment by Jen-Harris** [comment]
Ok, no worries. And would this be a mandatory question?

**Comment by kellygrellier** [comment]
Perhaps not, as long as we have there phone number and email as mandatory
that is the most important.

Thanks, Kelly

**Comment by Jen-Harris** [comment]
perfect, thanks!
