### ISSUE TITLE
Add GDPR inputs into email to Blue Cross

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/BlueCross#127]
Email needs to contain the contact preference and whether the user is happy to receive fundraising messages

**Comment by kellygrellier** [comment]
Hi @Jen-Harris,

I have copied this from my GDPR reply...
No the first one isn't legal and I was thinking we could leave it to,
"we will be in touch within 2 days to help you find a new home for 'name of dog'"
Rather than giving them the choice as we would rather call them.

Our legal secretary said that as they have filled out the form then they are requesting our services so it is fine to not ask them to confirm.

Thanks and sorry for being confusing!
