### ISSUE TITLE
Designs!

### ISSUE THREAD

**Issue by Jen-Harris** [InFact-coop/BlueCross#8]
Hey @kellysellier,
we've spent today trying to make the design ideas from yesterday more thorough and into something we feel is achievable in the time frame. 
The link for where we are designing these is [here](https://www.figma.com/file/f8BH9BNgYnLQxRtbnXNmUwTH/Blue-Cross) if you want a closer look. But I'll take you through step by step here as well. (all text is holding text until we have the questions!)

1. We imagine that the user would be greeted with the option of how urgently they would like to give up their pet. If they select urgently they will get an apology message asking them to call the help line and all the other options will provide them with a link to the next page 
  
![image](https://user-images.githubusercontent.com/26116988/33722104-fa9307cc-db60-11e7-8890-49484cae6ec7.png)

2. Then the user could go to the page which asks them about what pet they have, breed and age (we've currently chosen to follow only the dog flow)
  
![image](https://user-images.githubusercontent.com/26116988/33722167-2740f50e-db61-11e7-9543-f90baf3f7725.png)

  
3. Before going any further we thought it would make sense to ask the medical questions, as this feels like another natural place to triage?
  
![image](https://user-images.githubusercontent.com/26116988/33722377-ad43cc3a-db61-11e7-9f4e-3b6feb536298.png)

4. This isn't something we discussed specifically yesterday but we thought it would be nice to show the user a map when they enter their location of all the potential people looking for a pet similar to theirs at the moment. 
  
![image](https://user-images.githubusercontent.com/26116988/33722436-d9dd8650-db61-11e7-9e1b-4abd27ef046c.png)
  
5. We could then move onto personality questions
  
![image](https://user-images.githubusercontent.com/26116988/33722448-e7a44468-db61-11e7-9364-3036c2183dda.png)

6.  This could then lead to a page called 'their new home' which would cover likes, dislikes and desirable things for the new owner
  
![image](https://user-images.githubusercontent.com/26116988/33723026-695a46c8-db63-11e7-8cc8-f59aa153ffa6.png)

7. Basic questions for the owner so BX can get in touch with them 

![image](https://user-images.githubusercontent.com/26116988/33722680-8f56c5b4-db62-11e7-955c-09bf612f78ee.png)

  8. Then a thank you page! This could give the user an idea of next steps as well 
  
![image](https://user-images.githubusercontent.com/26116988/33722692-96fb213e-db62-11e7-8bd1-d7ff2b65e23e.png)

__questions__
* Does this flow meet your expectations? Is there anything you would change?
* Does the overall design look good to you? Are then any amendment you would like? 
* Any other comments on the design? 

Thanks!

**Comment by kellygrellier** [comment]
Hi @Jen-Harris 
It is looking amazing! 
1. We thought following just dog for skateboard is a good idea too.
Flow & Questions:
1. Giving a pet - we were thinking Find a new home for my pet I really like the description you have put underneath.
2. Next we thought What is your pet (and like you say just follow dog flow)
3. Then we thought it would be neat to ask them what the name is of their dog so we can then populate the questions with the name of their pet so it is personalised.
4. Then we thought we could find out the urgency - I really like how you have illustrated this the only change I would make is rather than under one week put 2- 3 weeks (if they put urgently it would be good to have a pop up that says we will be in touch within 24 hrs)
5. Then into about your pet, we have tried to keep the basic info to a minimum as follows:
Breed (we will give you a drop down menu)
Male / Female
Is 'Rex' Microchipped, Neutered, Vaccinated (don't put in wormed)
When was Rex's last visit to the vets within month/3 months/6 months/1 year/18 months or more
6. On Personality we thought it would be good to give them a whole list of words to check against - this will give us a really good feel for the dogs personality, also we could use it to populate the advert so Rex's owners said he is - and then show a word cloud in the shape of the blue cross logo?
7. Rather than new owners home we thought it would be good to have So we find Rex a home he loves where would he put his paw and then show sliding scales for:
CATS - love, Lives with, Tolerates, Chases, No thanks!
CHILDREN - Loves, Okay if they leave me alone, on my terms, No thanks!
UNFAMILIAR PEOPLE - Loves, in my home, in small numbers, not on my patch, Outside, No Thanks!
8. We thought they could then upload photos & videos 
9. I agree about a map and putting in their postcode (this will also allow us to see how far they are from our rehoming centres and how much potential additional support we could provide)
10. We thought we could give them a choice of support as follows:
A: They chat to prospective owners directly and rehome from home
B: Rehome from home but Blue Cross help them find owners
C: Blue Cross look after at their centre and rehome for them
11. Then they provide their details 
12. We thought it would be good to have a what happens next based on what they have chosen so:
If they chose A then 'your advert will appear and you can get started staright away
If they chose B or C then someone from Blue Cross will be in touch within 24 hrs if they said urgent or 4 working days if they said 2 weeks or more)
12 We would also like to have a 'Be Safe' button somewhere to provide advice about meeting with people.

The overall design looks spot on, you have captured the Blue Cross Brand perfectly!  It would be great if we could get Pets change lives we change theirs somewhere help Rex change someones life for example?

Thanks so much!!

**Comment by Jen-Harris** [comment]
Hey @kellygrellier thanks for the feedback, all very clear! 

Just two questions: 
* In terms of the 'be safe' button we can work on this if we have time but don't think it should be a priority? 
* As this is now quite a lot of pages (absolutely fine!) we may have to reduce the functionality. i.e. the photo page will be unable to take photos and the map page will just be a still image. Again, we really want to get these working but at the moment we're working on getting the flow together so you have a more complete proof of concept. Does this sound OK to you? Or would you prefer to reduce the flow and focus more time on functionality? 

Thanks!

**Comment by kellygrellier** [comment]
Hi Jen

I agree Be safe button not a priority.

I think probably flow & content over functionality at this point, it would be good to get the sliders for choosing though.

Thanks, Kelly

**Comment by Jen-Harris** [comment]
Yes perfect @kellygrellier, we're definitely aiming to get the sliders done! Think it's a really nice feature 😄
